### ISSUE TITLE
Maybe we should cancel the comment support

### ISSUE THREAD

**Issue by frankfoot** [PESolver/pesolver.github.io#4]
Using Issues is fairly enough ww
@problem233

**Comment by problem233** [comment]
![r 1j v0y9dg d h rnrcfxb](https://user-images.githubusercontent.com/13145126/27251133-0a00ef4c-5373-11e7-9330-637d91dace15.jpg) 我加这个主要是为了可以快速在主页上进行讨论

**Comment by frankfoot** [comment]
...
先用Readme吧
而且也有其它的方案
不一定要多说的

**Comment by problem233** [comment]
我用的是 [gitment](https://github.com/imsun/gitment)
