### ISSUE TITLE
这个repo最近不怎么活跃啊、、

### ISSUE THREAD

**Issue by frankfoot** [PESolver/pesolver.github.io#6]
@problem233 这个repo的编辑成本太高了、、、现在看起来像是个blog、、、
我建议你坠吼把这玩意调整一下，至少能直接用markdown写post
就算主页上不能显示也行、、、、毕竟这个主要还是exchange idea的地方嘛
我实在是不擅长html和jekyll、、、我就直接扔文档进去了啊233

**Comment by frankfoot** [comment]
唔我发现最近我没搞PE的题、、、这的确是个重点23333

**Comment by problem233** [comment]
写post的时候把md文件丢_posts文件夹里，md文件要加一个头，像这样：
```markdown
title: <标题>
layout: post
---
↑这个三横分割头部和正文
```

**Comment by frankfoot** [comment]
喂喂
这个我会的啊
但是麻烦、、、

**Comment by frankfoot** [comment]
jekyll的东西麻烦的要死、、、格式很死板的、、、要不要把网站扔到/doc/下？

**Comment by problem233** [comment]
没有啊、、是markdown啊
如果要用代码框的话`{% highlight cpp %}{% endhighlight %}`好了
